#include "stdafx.h"
#include "RecentApplications.h"
#include "IniFile.h"
#include <iostream>
#include <stdexcept>
#include <shlwapi.h>
#include <atlbase.h>
#include <shlobj.h>

CWinApp application;
using namespace RecentApplications;

static void Check(BOOL value, const char* description)
{
	if (!value) { std::cerr << "FAIL: " << description << " error=" << GetLastError() << "\n"; throw std::runtime_error(description); }
}

struct Fixture
{
	CString directory;
	Fixture()
	{
		WCHAR root[MAX_PATH], path[MAX_PATH]; GetTempPath(_countof(root), root);
		Check(GetTempFileName(root, L"PLT", 0, path) != 0, "temporary fixture");
		Check(DeleteFile(path) && CreateDirectory(path, NULL), "fixture directory"); directory = path;
	}
	CString Path(LPCWSTR name) { return directory + L"\\" + name; }
	~Fixture()
	{
		// Only explicit files generated by this fixture, never recursively delete.
		const LPCWSTR names[] = {L"recent.ini", L"writers.ini", L"sample.lnk", L"validated.ini", L"different.ini", L"profiles.ini", L"long.ini"};
		for (size_t i = 0; i < _countof(names); ++i) DeleteFile(Path(names[i]));
		RemoveDirectory(directory);
	}
};

static Entry Item(int index)
{
	Entry e; e.app.name.Format(L"Application %d", index);
	WCHAR exe[MAX_PATH]; GetModuleFileName(NULL, exe, _countof(exe)); e.app.path = exe;
	e.app.arguments.Format(L"--item=%d", index); return e;
}

static void SaveShortcut(const CString& path, const CString& target, LPCWSTR arguments)
{
	CComPtr<IShellLinkW> link; Check(SUCCEEDED(link.CoCreateInstance(CLSID_ShellLink)), "shortcut instance");
	Check(SUCCEEDED(link->SetPath(target)) && SUCCEEDED(link->SetArguments(arguments)), "shortcut fields");
	CComQIPtr<IPersistFile> file(link); Check(file && SUCCEEDED(file->Save(path, TRUE)), "shortcut save");
}

static void Seed(const CString& path, const CString& profile = L"A")
{
	CIniFile ini; ini.SetIniFileName(path);
	Check(ini.SetString(L"proxy_" + profile, L"Type", L"SOCKS5"), "seed profile");
	Check(ini.SetString(L"options", L"preserve", L"original"), "seed unrelated option");
}
static void TestStore(Fixture& f)
{
	Seed(f.Path(L"recent.ini"));
	Store store(L"A", f.Path(L"recent.ini")); std::vector<Entry> rows;
	Check(store.Read(rows) && rows.empty(), "missing history is empty");
	Entry original = Item(0); original.app.arguments = L"--title=\"Unicode \x4e2d\x6587\"\r\n--CaseSensitive";
	original.app.workingDirectory = f.directory;
	Check(store.Remember(original), "remember");
	Check(Store(L"A", f.Path(L"recent.ini")).Read(rows) && rows.size() == 1 && rows[0].app.arguments == original.app.arguments &&
		rows[0].app.workingDirectory == original.app.workingDirectory, "reload preserves Unicode arguments and cwd");
	CString id = rows[0].id; Check(store.SetPinned(id, TRUE), "pin");
	original.app.path.MakeUpper(); Check(store.Remember(original), "case-insensitive path duplicate");
	Check(store.Read(rows) && rows.size() == 1 && rows[0].id == id && rows[0].pinned, "dedup preserves pin and id");
	original.app.arguments.MakeLower(); Check(store.Remember(original), "arguments remain case-sensitive");
	original.elevated = TRUE; Check(store.Remember(original), "elevation remains distinct");
	Check(store.Read(rows) && rows.size() == 3, "different launch modes retained");
	for (int i = 1; i <= 25; ++i) Check(store.Remember(Item(i)), "bounded history append");
	Check(store.Read(rows) && rows.size() == 21 && rows[0].id == id && rows[0].pinned && rows[1].app.name == L"Application 25", "twenty recent plus pin, newest first");
	Check(store.SetPinned(id, FALSE) && store.Read(rows) && rows.size() == 20, "unpin applies history bound");
	Check(store.Remove(rows[0].id) && store.Read(rows) && rows.size() == 19, "remove persists");
	Entry missing = Item(90); missing.app.path = f.Path(L"missing.exe");
	InstalledApplications::Application resolved;
	Check(store.Remember(missing) && !Resolve(missing, resolved), "missing target not silently forgotten or launched");
	Entry packaged; packaged.app.name = L"Packaged"; packaged.app.aumid = L"Example_family!App";
	Check(store.Remember(packaged) && store.Read(rows) && rows[0].app.IsPackaged() && rows[0].app.aumid == packaged.app.aumid, "AUMID persisted");
	CString shortcut = f.Path(L"sample.lnk"); SaveShortcut(shortcut, Item(0).app.path, L"--before");
	Check(InstalledApplications::ResolveShortcut(shortcut, resolved), "shortcut resolves");
	Entry linked = FromApplication(resolved, FALSE);
	Check(linked.shortcut == shortcut, "shortcut origin extracted from launch metadata");
	Check(store.Remember(linked) && store.Read(rows) && rows[0].shortcut == shortcut, "shortcut origin persisted");
	SaveShortcut(shortcut, Item(0).app.path, L"--after");
	Check(Resolve(rows[0], resolved) && resolved.arguments == L"--after", "shortcut re-resolved on reuse");
	Entry oversized = Item(99); oversized.app.arguments = CString(L'x', 32768);
	Check(!store.Remember(oversized) && store.Read(rows), "oversized update preserves valid history");
	CIniFile ini; ini.SetIniFileName(f.Path(L"recent.ini"));
	Check(ini.GetString(L"options", L"preserve") == L"original", "options untouched");
	Check(ini.SetString(L"recent_app_" + rows[0].profileId + L"_" + rows[0].id, L"Version", L"broken"), "corrupt entry");
	Check(!store.Read(rows) && !store.Remember(Item(1)), "corrupt record not overwritten");
	std::cout << "persistence, dedup, pinning, cap, AUMID, shortcut, corruption: PASS\n";
}

static void TestWriters(Fixture& f, BOOL different)
{
	const CString path = f.Path(different ? L"different.ini" : L"writers.ini");
	Seed(path); Seed(path, L"B");
	WCHAR exe[MAX_PATH]; GetModuleFileName(NULL, exe, _countof(exe));
	PROCESS_INFORMATION children[3] = {};
	for (int i = 0; i < 3; ++i)
	{
		CString command;
		if (i < 2) command.Format(L"\"%s\" --writer \"%s\" %d %s", exe, static_cast<LPCWSTR>(path), i * 10, different && i == 1 ? L"B" : L"A");
		else command.Format(L"\"%s\" --settings \"%s\"", exe, static_cast<LPCWSTR>(path));
		STARTUPINFO si = {sizeof(si)};
		Check(CreateProcess(NULL, command.GetBuffer(), NULL, NULL, FALSE, CREATE_NO_WINDOW, NULL, NULL, &si, &children[i]), "start writer"); command.ReleaseBuffer();
	}
	BOOL passed = TRUE;
	for (int i = 0; i < 3; ++i)
	{
		if (WaitForSingleObject(children[i].hProcess, 20000) != WAIT_OBJECT_0) { TerminateProcess(children[i].hProcess, 99); passed = FALSE; }
		DWORD code = 1; GetExitCodeProcess(children[i].hProcess, &code); passed = passed && code == 0;
		CloseHandle(children[i].hThread); CloseHandle(children[i].hProcess);
	}
	std::vector<Entry> rows, b;
	Check(passed && Store(L"A", path).Read(rows) && rows.size() == (different ? 10 : 20), "no lost updates");
	Check(Store(L"B", path).Read(b) && b.size() == (different ? 10 : 0), "profiles isolated");
	CIniFile ini; ini.SetIniFileName(path);
	Check(ini.GetInt(L"options", L"counter", -1) == 99 && ini.GetString(L"proxy_A", L"Host") == L"concurrent", "independent settings survive");
	std::cout << (different ? "different-profile" : "same-profile") << " + independent settings writers: PASS\n";
}

static void TestProfileIsolation(Fixture& f)
{
	const CString path = f.Path(L"profiles.ini"); Seed(path); Seed(path, L"B");
	Store a(L"A", path), b(L"B", path);
	Check(a.Remember(Item(1)) && b.Remember(Item(1)), "same target in two profiles");
	std::vector<Entry> ar, br;
	Check(a.Read(ar) && b.Read(br) && ar.size() == 1 && br.size() == 1 && ar[0].profileId != br[0].profileId && ar[0].id != br[0].id, "independent identities");
	Check(a.SetPinned(ar[0].id, TRUE) && b.Read(br) && !br[0].pinned, "pin A only");
	Check(a.Remove(ar[0].id) && a.Read(ar) && ar.empty() && b.Read(br) && br.size() == 1, "remove A only");
	Check(a.Remember(Item(2)) && a.Read(ar), "A history");
	const CString oldId = ar[0].profileId;
	Store stale(L"A", path, oldId);
	Check(DeleteProfile(L"A", path) && stale.Read(ar) && ar.empty() && !stale.Remember(Item(3)), "deleted profile not resurrected");
	Seed(path);
	CString newId; Check(EnsureProfileId(L"A", newId, path) && newId != oldId, "recreated identity");
	Check(!stale.Remember(Item(3)) && stale.Read(ar) && ar.empty(), "old runtime cannot write new profile");
	Check(Store(L"A", path, newId).Remember(Item(4)) && b.Read(br) && br.size() == 1, "new A works, B retained");
	Check(Store(L"", path).Read(ar) && ar.empty(), "stopped context empty");
	std::cout << "profile isolation, deletion/recreation and stale runtime: PASS\n";
}

static void TestIniWrapper(Fixture& f)
{
	CIniFile ini; ini.SetIniFileName(f.Path(L"long.ini"));
	CString value(L'x', 12000);
	Check(ini.SetString(L"test", L"long", value) && ini.GetString(L"test", L"long") == value, "long value past old 4352 buffer");
	CString section(L's', 200), key(L'k', 200);
	Check(ini.SetString(section, key, L"value"), "long names");
	std::list<CString> sections, keys;
	Check(ini.GetSectionList(sections) == 2 && ini.GetKeyList(section, keys) == 1 && keys.front() == key, "no 128-char truncation");
	CIniFile::Section fields; fields[L"one"] = L"value"; fields[L"two"] = CString(L'a', 10000);
	Check(ini.WriteSection(L"atomic", fields), "whole-section write");
	CIniFile::Section loaded;
	Check(ini.ReadSection(L"atomic", loaded) && fields == loaded, "whole-section round trip");
	Entry entry = Item(1); entry.app.arguments = L"  \"quoted\"\r\n" + CString(L'x', 12000) + L"  ";
	Seed(f.Path(L"long.ini"));
	Check(Store(L"A", f.Path(L"long.ini")).Remember(entry), "long argument save");
	std::vector<Entry> rows;
	Check(Store(L"A", f.Path(L"long.ini")).Read(rows) && rows[0].app.arguments == entry.app.arguments, "quotes, whitespace and long args preserved");
	std::cout << "INI long names/values, section I/O and argument encoding: PASS\n";
}

static void TestCatalogIntegration(Fixture& f)
{
	Entry recent = Item(700);
	InstalledApplications::Application catalog = recent.app;
	catalog.path.MakeUpper();
	Check(MatchesCatalog(recent, catalog), "catalog/recent path dedup");
	recent.available = FALSE;
	Check(!MatchesCatalog(recent, catalog), "unavailable recent must not hide usable catalog target");
	recent.available = TRUE;
	catalog.arguments += L" --different";
	Check(!MatchesCatalog(recent, catalog), "different arguments remain available");
	catalog = recent.app; recent.app.workingDirectory = L"C:/Example/";
	Check(MatchesCatalog(recent, catalog), "missing catalog cwd matches recent metadata");
	catalog.workingDirectory = L"c:\\example";
	Check(MatchesCatalog(recent, catalog), "cwd normalization matches");
	catalog.workingDirectory = L"C:\\Other";
	Check(!MatchesCatalog(recent, catalog), "different explicit cwd preserved");
	recent.app.aumid = L"Example_family!App"; catalog = recent.app; catalog.path.Empty();
	Check(MatchesCatalog(recent, catalog), "packaged target identified by AUMID");
	catalog.aumid = L"Other_family!App";
	Check(!MatchesCatalog(recent, catalog), "different AUMID preserved");
	Seed(f.Path(L"validated.ini"));
	Store store(L"A", f.Path(L"validated.ini"));
	Check(store.Remember(Item(700)), "validation fixture existing target");
	Entry missing = Item(701); missing.app.path = f.Path(L"missing.exe");
	Check(store.Remember(missing), "validation fixture missing target");
	CString identity; Check(EnsureProfileId(L"A", identity, f.Path(L"validated.ini")), "validation ID");
	Load* load = BeginLoad(L"A", f.Path(L"validated.ini"), identity);
	BOOL done = FALSE;
	const DWORD started = GetTickCount();
	while (!done && GetTickCount() - started < 10000)
	{
		EnterCriticalSection(&load->lock); done = load->done; LeaveCriticalSection(&load->lock);
		if (!done) Sleep(10);
	}
	const BOOL valid = done && load->succeeded && load->entries.size() == 2 &&
		!load->entries[0].available && load->entries[0].app.path == missing.app.path &&
		load->entries[0].app.name == missing.app.name && !load->entries[0].id.IsEmpty() &&
		load->entries[1].available && load->entries[1].app.arguments == Item(700).app.arguments;
	if (load->cancel) SetEvent(load->cancel);
	load->Release();
	Check(valid, "background validation retains missing targets as unavailable");
	std::vector<Entry> saved;
	Check(store.Read(saved) && saved.size() == 2, "validation does not permanently erase inaccessible entries");
	Check(saved[0].available, "availability is transient and rechecked on reload");
	Check(store.Remove(saved[0].id), "unavailable entry can be explicitly removed");
	Check(store.Read(saved) && saved.size() == 1 && saved[0].app.arguments == Item(700).app.arguments,
		"removing unavailable entry preserves usable history");
	std::cout << "catalog merge identity and background validation: PASS\n";
}

int wmain(int argc, wchar_t** argv)
{
	if (!AfxWinInit(GetModuleHandle(NULL), NULL, GetCommandLine(), 0)) return 2;
	CoInitialize(NULL); int result = 0;
	try
	{
		if (argc == 5 && wcscmp(argv[1], L"--writer") == 0)
		{
			Store store(argv[4], argv[2]); int base = _wtoi(argv[3]);
			for (int i = 0; i < 10; ++i) Check(store.Remember(Item(base + i)), "writer remember");
		}
		else if (argc == 3 && wcscmp(argv[1], L"--settings") == 0)
		{
			CIniFile ini; ini.SetIniFileName(argv[2]);
			for (int i = 0; i < 100; ++i)
			{
				Check(ini.SetInt(L"options", L"counter", i), "concurrent option");
				Check(ini.SetString(L"proxy_A", L"Host", L"concurrent"), "concurrent host");
			}
		}
		else { Fixture fixture; TestStore(fixture); TestWriters(fixture, FALSE); TestWriters(fixture, TRUE); TestProfileIsolation(fixture); TestIniWrapper(fixture); TestCatalogIntegration(fixture); }
	}
	catch (const std::exception&) { result = 1; }
	CoUninitialize(); return result;
}
